use serde::{Deserialize, Serialize};

use super::message::{ChatFunctionCallArgs, ChatMessageToolCall};

/// Processing tier used to serve a request.
///
/// ```
/// use lutum_openai::chat::ServiceTier;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(r#""auto""#).unwrap();
/// let val = serde_json::from_value::<ServiceTier>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<ServiceTier>(json).unwrap(), val);
/// ```
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ServiceTier {
    Auto,
    Default,
    Flex,
    Scale,
    Priority,
}

/// URL citation annotation returned when using the web search tool.
///
/// ```
/// use lutum_openai::chat::UrlCitation;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(
///     r#"{"end_index":42,"start_index":10,"title":"Example","url":"https://example.com"}"#,
/// )
/// .unwrap();
/// let val = serde_json::from_value::<UrlCitation>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<UrlCitation>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct UrlCitation {
    pub end_index: u64,
    pub start_index: u64,
    pub title: String,
    pub url: String,
}

/// An annotation on a chat completion message.
///
/// ```
/// use lutum_openai::chat::ChatCompletionAnnotation;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(
///     r#"{"type":"url_citation","url_citation":{"end_index":42,"start_index":10,"title":"Example","url":"https://example.com"}}"#,
/// )
/// .unwrap();
/// let val = serde_json::from_value::<ChatCompletionAnnotation>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<ChatCompletionAnnotation>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ChatCompletionAnnotation {
    UrlCitation { url_citation: UrlCitation },
}

/// Audio output from the model.
///
/// ```
/// use lutum_openai::chat::ChatCompletionAudio;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(
///     r#"{"id":"audio_abc","data":"base64==","expires_at":1700000000,"transcript":"Hello!"}"#,
/// )
/// .unwrap();
/// let val = serde_json::from_value::<ChatCompletionAudio>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<ChatCompletionAudio>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionAudio {
    pub id: String,
    pub data: String,
    pub expires_at: u64,
    pub transcript: String,
}

/// The assistant message generated by the model in a completion choice.
///
/// `content` and `refusal` are always present in the wire format (possibly as
/// `null`), so they serialize as `null` when `None`.
///
/// ```
/// use lutum_openai::chat::ChatCompletionMessage;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(
///     r#"{"content":"Hello!","refusal":null,"role":"assistant"}"#,
/// )
/// .unwrap();
/// let val = serde_json::from_value::<ChatCompletionMessage>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<ChatCompletionMessage>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionMessage {
    pub content: Option<String>,
    pub refusal: Option<String>,
    pub role: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub annotations: Option<Vec<ChatCompletionAnnotation>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio: Option<ChatCompletionAudio>,
    /// Deprecated — use `tool_calls` instead.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_call: Option<ChatFunctionCallArgs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ChatMessageToolCall>>,
}

/// Reason the model stopped generating tokens.
///
/// ```
/// use lutum_openai::chat::ChatFinishReason;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(r#""stop""#).unwrap();
/// let val = serde_json::from_value::<ChatFinishReason>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<ChatFinishReason>(json).unwrap(), val);
/// ```
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ChatFinishReason {
    Stop,
    Length,
    ToolCalls,
    ContentFilter,
    FunctionCall,
}

/// Top-N most likely token at a given position with its log probability.
///
/// ```
/// use lutum_openai::chat::TopLogprob;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(
///     r#"{"token":"hello","bytes":[104,101,108,108,111],"logprob":-0.5}"#,
/// )
/// .unwrap();
/// let val = serde_json::from_value::<TopLogprob>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<TopLogprob>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopLogprob {
    pub token: String,
    pub bytes: Vec<u8>,
    pub logprob: f64,
}

/// Log probability information for a single output token.
///
/// ```
/// use lutum_openai::chat::ChatCompletionTokenLogprob;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(
///     r#"{"token":"hi","bytes":[104,105],"logprob":-0.1,"top_logprobs":[]}"#,
/// )
/// .unwrap();
/// let val = serde_json::from_value::<ChatCompletionTokenLogprob>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<ChatCompletionTokenLogprob>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionTokenLogprob {
    pub token: String,
    pub bytes: Vec<u8>,
    pub logprob: f64,
    pub top_logprobs: Vec<TopLogprob>,
}

/// Log probability information for a completion choice.
///
/// ```
/// use lutum_openai::chat::ChoiceLogprobs;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(r#"{"content":null,"refusal":null}"#).unwrap();
/// let val = serde_json::from_value::<ChoiceLogprobs>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<ChoiceLogprobs>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChoiceLogprobs {
    pub content: Option<Vec<ChatCompletionTokenLogprob>>,
    pub refusal: Option<Vec<ChatCompletionTokenLogprob>>,
}

/// One completion choice from the model.
///
/// ```
/// use lutum_openai::chat::ChatCompletionChoice;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(
///     r#"{"finish_reason":"stop","index":0,"logprobs":null,"message":{"content":"Hi!","refusal":null,"role":"assistant"}}"#,
/// )
/// .unwrap();
/// let val = serde_json::from_value::<ChatCompletionChoice>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<ChatCompletionChoice>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionChoice {
    pub finish_reason: ChatFinishReason,
    pub index: u32,
    pub logprobs: Option<ChoiceLogprobs>,
    pub message: ChatCompletionMessage,
}

/// Breakdown of completion tokens.
///
/// ```
/// use lutum_openai::chat::CompletionTokensDetails;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(r#"{"reasoning_tokens":5}"#).unwrap();
/// let val = serde_json::from_value::<CompletionTokensDetails>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<CompletionTokensDetails>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct CompletionTokensDetails {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accepted_prediction_tokens: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio_tokens: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_tokens: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rejected_prediction_tokens: Option<u64>,
}

/// Breakdown of prompt tokens.
///
/// ```
/// use lutum_openai::chat::PromptTokensDetails;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(r#"{"cached_tokens":10}"#).unwrap();
/// let val = serde_json::from_value::<PromptTokensDetails>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<PromptTokensDetails>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct PromptTokensDetails {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio_tokens: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cached_tokens: Option<u64>,
}

/// Token usage statistics for a completion request.
///
/// ```
/// use lutum_openai::chat::CompletionUsage;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(
///     r#"{"completion_tokens":10,"prompt_tokens":5,"total_tokens":15}"#,
/// )
/// .unwrap();
/// let val = serde_json::from_value::<CompletionUsage>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<CompletionUsage>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct CompletionUsage {
    pub completion_tokens: u64,
    pub prompt_tokens: u64,
    pub total_tokens: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completion_tokens_details: Option<CompletionTokensDetails>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_tokens_details: Option<PromptTokensDetails>,
}

/// A complete chat completion response from the model.
///
/// ```
/// use lutum_openai::chat::ChatCompletion;
/// use serde_json::Value;
///
/// let json = serde_json::from_str::<Value>(
///     r#"{"id":"chatcmpl-abc","choices":[{"finish_reason":"stop","index":0,"logprobs":null,"message":{"content":"Hello!","refusal":null,"role":"assistant"}}],"created":1741569952,"model":"gpt-4o","object":"chat.completion"}"#,
/// )
/// .unwrap();
/// let val = serde_json::from_value::<ChatCompletion>(json.clone()).unwrap();
/// assert_eq!(serde_json::to_value(&val).unwrap(), json);
/// assert_eq!(serde_json::from_value::<ChatCompletion>(json).unwrap(), val);
/// ```
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletion {
    pub id: String,
    pub choices: Vec<ChatCompletionChoice>,
    pub created: u64,
    pub model: String,
    pub object: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<ServiceTier>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_fingerprint: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<CompletionUsage>,
}
