use std::sync::Arc;

use futures::executor::block_on;
use lutum::{
    FinishReason, MockLlmAdapter, MockTextScenario, ModelInputItem, RawTextTurnEvent, Session,
    SharedPoolBudgetManager, SharedPoolBudgetOptions, TextStepOutcomeWithTools, ToolDecision,
    ToolMetadata, ToolRoundPlan, Usage,
};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, JsonSchema)]
struct WeatherResult {
    forecast: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, JsonSchema)]
struct SearchResult {
    hits: Vec<String>,
}

#[lutum::tool_input(name = "weather", output = WeatherResult)]
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, JsonSchema)]
struct WeatherArgs {
    city: String,
}

#[lutum::tool_input(name = "search", output = SearchResult)]
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, JsonSchema)]
struct SearchArgs {
    query: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, JsonSchema, lutum::Toolset)]
enum Tools {
    Weather(WeatherArgs),
    Search(SearchArgs),
}

fn execute_weather(input: &WeatherArgs) -> WeatherResult {
    WeatherResult {
        forecast: format!("live forecast for {}: 24C and sunny", input.city),
    }
}

fn execute_search(input: &SearchArgs) -> SearchResult {
    SearchResult {
        hits: vec![
            format!("Top result for {}", input.query),
            format!("Backup result for {}", input.query),
        ],
    }
}

// A cache-backed weather hook defined with #[impl_hook].
// The generated `CachedWeather` struct is placed in the same scope as
// `ToolsHooks`, so it can be passed directly to `with_weather_hook`.
#[lutum::impl_hook(WeatherHook)]
async fn cached_weather(
    _metadata: &ToolMetadata,
    input: WeatherArgs,
) -> ToolDecision<WeatherArgs, WeatherResult> {
    match input.city.as_str() {
        "Tokyo" => ToolDecision::Complete(WeatherResult {
            forecast: "cached: 22C and clear".into(),
        }),
        _ => ToolDecision::RunNormally(input),
    }
}

async fn run() -> Result<(), Box<dyn std::error::Error>> {
    let adapter = MockLlmAdapter::new().with_text_scenario(MockTextScenario::events(vec![
        Ok(RawTextTurnEvent::Started {
            request_id: Some("req-tool-hook".into()),
            model: "gpt-4.1-mini".into(),
        }),
        Ok(RawTextTurnEvent::ToolCallChunk {
            id: "call-weather".into(),
            name: "weather".into(),
            arguments_json_delta: "{\"city\":\"Tokyo\"}".into(),
        }),
        Ok(RawTextTurnEvent::ToolCallChunk {
            id: "call-search".into(),
            name: "search".into(),
            arguments_json_delta: "{\"query\":\"lunch near Tokyo Station\"}".into(),
        }),
        Ok(RawTextTurnEvent::Completed {
            request_id: Some("req-tool-hook".into()),
            finish_reason: FinishReason::ToolCall,
            usage: Usage::zero(),
        }),
    ]));

    let ctx = lutum::Lutum::new(
        Arc::new(adapter),
        SharedPoolBudgetManager::new(SharedPoolBudgetOptions::default()),
    );
    let mut session = Session::new(ctx);
    session.push_user("Check Tokyo weather, then search for lunch near Tokyo Station.");

    // Tool hooks are generated by `#[derive(Toolset)]` via the `#[hooks]` machinery.
    // `with_weather_hook` accepts any value implementing the generated `WeatherHook` trait.
    // `CachedWeather` is generated by `#[impl_hook(WeatherHook)]` above.
    let tool_hooks = ToolsHooksSet::new().with_weather_hook(CachedWeather);

    let round = match session
        .text_turn()
        .tools::<Tools>()
        .available_tools([ToolsSelector::Weather, ToolsSelector::Search])
        .collect()
        .await?
    {
        TextStepOutcomeWithTools::NeedsTools(round) => round,
        TextStepOutcomeWithTools::Finished(result) => {
            println!(
                "assistant replied without tools: {}",
                result.assistant_text()
            );
            return Ok(());
        }
    };

    // Apply hooks in batch — weather hits the cache, search stays pending.
    let plan: ToolRoundPlan<Tools> = round.apply_hooks(&tool_hooks).await;

    for handled in &plan.handled {
        match handled {
            ToolsHandled::Weather(h) => {
                println!("hook handled weather({}) from cache", h.input().city)
            }
            ToolsHandled::Search(h) => println!("hook handled search({})", h.input().query),
        }
    }

    // Execute remaining pending calls.
    let pending_results: Vec<_> = plan
        .pending
        .iter()
        .map(|call| match call {
            ToolsCall::Weather(c) => {
                println!("cache miss, executing weather tool for {}", c.input().city);
                WeatherArgs::tool_result(c.metadata.clone(), execute_weather(c.input()))
            }
            ToolsCall::Search(c) => {
                println!("no hook for search, executing the normal tool code");
                SearchArgs::tool_result(c.metadata.clone(), execute_search(c.input()))
            }
        })
        .collect::<Result<_, _>>()?;

    plan.commit(&mut session, pending_results)?;

    println!("\nCommitted tool results:");
    for item in session.input().items() {
        if let ModelInputItem::ToolResult(result) = item {
            match result.name.as_str() {
                "weather" => {
                    let weather: WeatherResult = result.result.deserialize()?;
                    println!("- weather: {}", weather.forecast);
                }
                "search" => {
                    let search: SearchResult = result.result.deserialize()?;
                    println!("- search: {:?}", search.hits);
                }
                _ => {}
            }
        }
    }

    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    block_on(run())
}
