use std::{collections::HashMap, sync::Arc};

use futures::executor::block_on;
use lutum::{
    FinishReason, MockLlmAdapter, MockTextScenario, ModelInputItem, RawTextTurnEvent, Session,
    SharedPoolBudgetManager, SharedPoolBudgetOptions, TextStepOutcomeWithTools, ToolHookOutcome,
    ToolMetadata, Usage,
};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, JsonSchema)]
struct WeatherResult {
    forecast: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, JsonSchema)]
struct SearchResult {
    hits: Vec<String>,
}

#[lutum::tool_input(name = "weather", output = WeatherResult)]
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, JsonSchema)]
struct WeatherArgs {
    city: String,
}

#[lutum::tool_input(name = "search", output = SearchResult)]
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, JsonSchema)]
struct SearchArgs {
    query: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, JsonSchema, lutum::Toolset)]
enum Tools {
    Weather(WeatherArgs),
    Search(SearchArgs),
}

fn execute_weather(input: &WeatherArgs) -> WeatherResult {
    WeatherResult {
        forecast: format!("live forecast for {}: 24C and sunny", input.city),
    }
}

fn execute_search(input: &SearchArgs) -> SearchResult {
    SearchResult {
        hits: vec![
            format!("Top result for {}", input.query),
            format!("Backup result for {}", input.query),
        ],
    }
}

async fn run() -> Result<(), Box<dyn std::error::Error>> {
    let adapter = MockLlmAdapter::new().with_text_scenario(MockTextScenario::events(vec![
        Ok(RawTextTurnEvent::Started {
            request_id: Some("req-tool-hook".into()),
            model: "gpt-4.1-mini".into(),
        }),
        Ok(RawTextTurnEvent::ToolCallChunk {
            id: "call-weather".into(),
            name: "weather".into(),
            arguments_json_delta: "{\"city\":\"Tokyo\"}".into(),
        }),
        Ok(RawTextTurnEvent::ToolCallChunk {
            id: "call-search".into(),
            name: "search".into(),
            arguments_json_delta: "{\"query\":\"lunch near Tokyo Station\"}".into(),
        }),
        Ok(RawTextTurnEvent::Completed {
            request_id: Some("req-tool-hook".into()),
            finish_reason: FinishReason::ToolCall,
            usage: Usage::zero(),
        }),
    ]));

    let ctx = lutum::Lutum::new(
        Arc::new(adapter),
        SharedPoolBudgetManager::new(SharedPoolBudgetOptions::default()),
    );
    let mut session = Session::new(ctx);
    session.push_user("Check Tokyo weather, then search for lunch near Tokyo Station.");

    let weather_cache = Arc::new(HashMap::from([(
        "Tokyo".to_owned(),
        WeatherResult {
            forecast: "cached forecast for Tokyo: 22C and clear".into(),
        },
    )]));

    // Tool hooks are generated by `#[derive(Toolset)]`.
    // Return `Some(output)` to short-circuit execution, or `None` to fall back to normal tool code.
    let tool_hooks = ToolsHooks::new().with_weather({
        let weather_cache = Arc::clone(&weather_cache);
        move |_metadata: &ToolMetadata, input: &WeatherArgs| {
            let cached = weather_cache.get(&input.city).cloned();
            async move { cached }
        }
    });

    let round = match session
        .text_turn()
        .tools::<Tools>()
        .available_tools([ToolsSelector::Weather, ToolsSelector::Search])
        .collect()
        .await?
    {
        TextStepOutcomeWithTools::NeedsTools(round) => round,
        TextStepOutcomeWithTools::Finished(result) => {
            println!(
                "assistant replied without tools: {}",
                result.assistant_text()
            );
            return Ok(());
        }
    };

    let mut tool_results = Vec::new();
    for call in round.tool_calls.iter().cloned() {
        let tool_result = match call.hook(&tool_hooks).await {
            ToolHookOutcome::Handled(ToolsHandled::Weather(handled)) => {
                println!(
                    "tool hook handled weather({}) from cache",
                    handled.input().city
                );
                handled.into_tool_result()?
            }
            ToolHookOutcome::Handled(ToolsHandled::Search(handled)) => {
                println!("tool hook handled search({})", handled.input().query);
                handled.into_tool_result()?
            }
            ToolHookOutcome::Unhandled(ToolsCall::Weather(call)) => {
                println!(
                    "cache miss, executing weather tool for {}",
                    call.input().city
                );
                WeatherArgs::tool_result(call.metadata.clone(), execute_weather(call.input()))?
            }
            ToolHookOutcome::Unhandled(ToolsCall::Search(call)) => {
                println!("no hook for search, executing the normal tool code");
                SearchArgs::tool_result(call.metadata.clone(), execute_search(call.input()))?
            }
        };
        tool_results.push(tool_result);
    }

    round.commit(&mut session, tool_results)?;

    println!("\nCommitted tool results:");
    for item in session.input().items() {
        if let ModelInputItem::ToolResult(result) = item {
            match result.name.as_str() {
                "weather" => {
                    let weather: WeatherResult = result.result.deserialize()?;
                    println!("- weather: {}", weather.forecast);
                }
                "search" => {
                    let search: SearchResult = result.result.deserialize()?;
                    println!("- search: {:?}", search.hits);
                }
                _ => {}
            }
        }
    }

    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    block_on(run())
}
